module.exports = {
  GOOD_MATCH_THRESHOLD: 40,
  DISTANCE_THRESHOLD: 2,
  DISTANCE_FULL_MATCH: 30,
  DISTANCE_THRESHOLD_LIMIT_START: 3,
  DISTANCE_THRESHOLD_LIMIT_END: 10,
  DISTANCE_PARTIAL_MATCH: 20,
  DISTANCE_DEFAULT_MATCH: 10,
  ROOM_MATCH_PERCENT: 20,
  BUDGET_MATCH_PERCENT: 30,
  BUDGET_PLUS_MINUS_PERCENT: 10
};